### ISSUE TITLE
Do we have more detailed instruction for usage?

### ISSUE THREAD

**Issue by Yat3s** [wechaty/openapi#25]
## 🐛 Bug Report
I tried to follow the instruction but looks like I unable to run it on my device
![image](https://user-images.githubusercontent.com/14801837/138542002-929c2d54-cf18-4756-a3e6-1e26e8ebd935.png)

I have tried to run this repo directly, but the same error occurred, so did I miss some steps or this tool doesn't work anymore？

**Comment by huan** [comment]
This repo is still under construction, if you want to make it work, it's not enough to use parameters with the cli command, but you need to modify the source code itself.

I was planing to finish for the past three months but unfortunately it has been delayed for many times.

I hope I can finish it in the Nov, please stay tuned.

**Comment by Yat3s** [comment]
Thanks, so do you have any other suggestions about managing the bot by REST API？

**Comment by huan** [comment]
You are welcome.

My suggestion for managing the bot by REST API will be to use our official OpenAPI module, which is under construction right here.

**Comment by Yat3s** [comment]
Gentle ping @huan

**Comment by huan** [comment]
We have some priority need to be implemented first which caused the delay of the openapi developments.

Please stay tuned and we hope can start implementing it in the early January.
